name: scheduled-batch-automation
on: [push]
jobs:
  check-bats-verson:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: node main.js